/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixabd;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Emanuel
 */
public class guiCaixa extends javax.swing.JFrame {

    /**
     * Creates new form guiCaixa
     */
    public guiCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSaldo = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        btnSomar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAviso = new javax.swing.JTextArea();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caixa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSaldo.setEnabled(false);
        getContentPane().add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 320, 40));

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 320, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        jLabel2.setText("Saldo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        jLabel1.setText("Valor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 110, 50));

        btnSomar.setText("Somar");
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 110, 50));

        txtAviso.setColumns(20);
        txtAviso.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtAviso.setRows(5);
        jScrollPane1.setViewportView(txtAviso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 420, 230));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-azul-abstrato-hd-4.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("Select * from tabela1");
            rs.next();
            txtSaldo.setText(rs.getString(1));
        } catch (SQLException ex) {
            txtAviso.append("Erro na consulta");
        }
            txtAviso.setText("Bem Vindo \n");
        
    }//GEN-LAST:event_formWindowOpened

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        try {
            //pega o valor do bd e soma com valor da txtValor
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("Select * from tabela1");
            rs.next();
            Double saldo = Double.valueOf(rs.getString(1));
            Double valor = saldo + Double.valueOf(txtValor.getText());
            txtValor.setText("");
            if(valor >= 0){
            //executa a bagaça toda
            PreparedStatement ps = cn.prepareStatement("UPDATE caixa.tabela1 SET saldo= ? WHERE "+saldo);
            ps.setString(1, valor.toString());
            ps.executeUpdate();
            //mostra o valor
            st = cn.createStatement();
            rs = st.executeQuery("Select * from tabela1");
            rs.next();
            txtSaldo.setText(rs.getString(1));
            
            txtAviso.setText("Soma efetuada\n");
            }else{
                txtAviso.append("Saldo Insuficiente");
            }
        } catch (SQLException ex) {
            txtAviso.append("Erro na soma");
          }
    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        try {
            //pega o valor do bd e soma com valor da txtValor
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("Select * from tabela1");
            rs.next();
            Double saldo = Double.valueOf(rs.getString(1));
            Double valor = saldo - Double.valueOf(txtValor.getText());
            txtValor.setText("");
            if(valor >= 0){
            //executa a bagaça toda
            PreparedStatement ps = cn.prepareStatement("UPDATE caixa.tabela1 SET saldo= ? WHERE "+saldo);
            ps.setString(1, valor.toString());
            ps.executeUpdate();
            //mostra o valor
            st = cn.createStatement();
            rs = st.executeQuery("Select * from tabela1");
            rs.next();
            txtSaldo.setText(rs.getString(1));
            
            txtAviso.setText("Retirada efetuada \n");
            }else{
                txtAviso.append("Saldo Insuficiente");
            }
        } catch (SQLException ex) {
            txtAviso.append("Erro na retirada");
          }
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiCaixa().setVisible(true);
            }
        });
    }
    conectar co = new conectar();
    Connection cn = co.conectar();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAviso;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
